package com.nuoshi.console.domain.photo;

public class RejectPhoto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reject_photo.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reject_photo.house_id
     *
     * @mbggenerated
     */
    private Integer houseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reject_photo.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reject_photo.photo_id
     *
     * @mbggenerated
     */
    
    private Integer photoType;
    
   

	private Integer photoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reject_photo.reason
     *
     * @mbggenerated
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reject_photo.photobrowse
     *
     * @mbggenerated
     */
    private String photobrowse;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reject_photo.id
     *
     * @return the value of reject_photo.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reject_photo.id
     *
     * @param id the value for reject_photo.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reject_photo.house_id
     *
     * @return the value of reject_photo.house_id
     *
     * @mbggenerated
     */
    public Integer getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reject_photo.house_id
     *
     * @param houseId the value for reject_photo.house_id
     *
     * @mbggenerated
     */
    public void setHouseId(Integer houseId) {
        this.houseId = houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reject_photo.type
     *
     * @return the value of reject_photo.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reject_photo.type
     *
     * @param type the value for reject_photo.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reject_photo.photo_id
     *
     * @return the value of reject_photo.photo_id
     *
     * @mbggenerated
     */
    public Integer getPhotoId() {
        return photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reject_photo.photo_id
     *
     * @param photoId the value for reject_photo.photo_id
     *
     * @mbggenerated
     */
    public void setPhotoId(Integer photoId) {
        this.photoId = photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reject_photo.reason
     *
     * @return the value of reject_photo.reason
     *
     * @mbggenerated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reject_photo.reason
     *
     * @param reason the value for reject_photo.reason
     *
     * @mbggenerated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reject_photo.photobrowse
     *
     * @return the value of reject_photo.photobrowse
     *
     * @mbggenerated
     */
    public String getPhotobrowse() {
        return photobrowse;
    }

    
    public Integer getPhotoType() {
		return photoType;
	}

	public void setPhotoType(Integer photoType) {
		this.photoType = photoType;
	}
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reject_photo.photobrowse
     *
     * @param photobrowse the value for reject_photo.photobrowse
     *
     * @mbggenerated
     */
    public void setPhotobrowse(String photobrowse) {
        this.photobrowse = photobrowse == null ? null : photobrowse.trim();
    }
}