package com.nuoshi.console.domain.bbs;

import com.nuoshi.console.service.ForumService;
import com.nuoshi.console.service.LocaleService;

public class Forumuser {

	private Integer id;

	private String username;
	private Integer roleid;
	private String rolename;
	private int status;
	private Integer cityid;
	private Integer forumid;
	private Integer userid;
	private int userRole;//用户身份(//经纪人｜普通用户)
	private String trueName;//(真实姓名)

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public String getRolename() {
		return rolename;
	}

	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

	public Integer getUserid() {
		return userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column forumuser.id
	 * 
	 * @param id
	 *            the value for forumuser.id
	 * @abatorgenerated Thu Feb 09 17:15:36 CST 2012
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column forumuser.name
	 * 
	 * @return the value of forumuser.name
	 * @abatorgenerated Thu Feb 09 17:15:36 CST 2012
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column forumuser.name
	 * 
	 * @param name
	 *            the value for forumuser.name
	 * @abatorgenerated Thu Feb 09 17:15:36 CST 2012
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	public Integer getRoleid() {
		return roleid;
	}

	public void setRoleid(Integer roleid) {
		this.roleid = roleid;
	}

	public Integer getCityid() {

		return cityid;
	}

	public void setCityid(Integer cityid) {
		if (cityid == null) {
			cityid = 0;
		}
		this.cityid = cityid;
	}

	public Integer getForumid() {
		return forumid;
	}

	public void setForumid(Integer forumid) {
		this.forumid = forumid;
	}

	public String getCityName() {
		return LocaleService.getName(this.getCityid());
	}

	public String getParent() {
		String p = null;
		String pp = null;
		System.out.println("id=" + this.getId());
		String name = "";
		TfBbsForums forum = ForumService.getForum(this.getForumid());
		if (forum != null) {
			name = forum.getName();
			if (forum.getParentId() > 0) {
				TfBbsForums pTmp = ForumService.getForum(forum.getParentId());
				if (pTmp != null) {
					p = pTmp.getName();
					if (pTmp.getParentId() > 0) {
						TfBbsForums ppTmp = ForumService.getForum(pTmp.getParentId());
						if (ppTmp != null) {
							pp = ppTmp.getName();
						}

					}
				}
			}
		}
		String parentStr = "";
		if (pp != null) {
			parentStr += pp + "-";
		}
		if (p != null) {
			parentStr += p + "-";
		}

		parentStr += name;
		return parentStr;
	}

	public int getUserRole() {
		return userRole;
	}

	public void setUserRole(int userRole) {
		this.userRole = userRole;
	}

	public String getTrueName() {
		return trueName;
	}

	public void setTrueName(String trueName) {
		this.trueName = trueName;
	}

}