package com.nuoshi.console.domain.bbs;

public class Function {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column function.ID
     *
     * @abatorgenerated Thu Feb 09 16:51:35 CST 2012
     */
    private Long id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column function.NAME
     *
     * @abatorgenerated Thu Feb 09 16:51:35 CST 2012
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column function.num
     *
     * @abatorgenerated Thu Feb 09 16:51:35 CST 2012
     */
    private Integer num;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column function.ID
     *
     * @return the value of function.ID
     *
     * @abatorgenerated Thu Feb 09 16:51:35 CST 2012
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column function.ID
     *
     * @param id the value for function.ID
     *
     * @abatorgenerated Thu Feb 09 16:51:35 CST 2012
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column function.NAME
     *
     * @return the value of function.NAME
     *
     * @abatorgenerated Thu Feb 09 16:51:35 CST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column function.NAME
     *
     * @param name the value for function.NAME
     *
     * @abatorgenerated Thu Feb 09 16:51:35 CST 2012
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column function.num
     *
     * @return the value of function.num
     *
     * @abatorgenerated Thu Feb 09 16:51:35 CST 2012
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column function.num
     *
     * @param num the value for function.num
     *
     * @abatorgenerated Thu Feb 09 16:51:35 CST 2012
     */
    public void setNum(Integer num) {
        this.num = num;
    }
}