package com.nuoshi.console.domain.bbs;

public class Role {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column role.id
     *
     * @abatorgenerated Thu Feb 09 16:54:14 CST 2012
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column role.code
     *
     * @abatorgenerated Thu Feb 09 16:54:14 CST 2012
     */
    private String code;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column role.name
     *
     * @abatorgenerated Thu Feb 09 16:54:14 CST 2012
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column role.status
     *
     * @abatorgenerated Thu Feb 09 16:54:14 CST 2012
     */
    private Integer status;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column role.id
     *
     * @return the value of role.id
     *
     * @abatorgenerated Thu Feb 09 16:54:14 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column role.id
     *
     * @param id the value for role.id
     *
     * @abatorgenerated Thu Feb 09 16:54:14 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column role.code
     *
     * @return the value of role.code
     *
     * @abatorgenerated Thu Feb 09 16:54:14 CST 2012
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column role.code
     *
     * @param code the value for role.code
     *
     * @abatorgenerated Thu Feb 09 16:54:14 CST 2012
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column role.name
     *
     * @return the value of role.name
     *
     * @abatorgenerated Thu Feb 09 16:54:14 CST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column role.name
     *
     * @param name the value for role.name
     *
     * @abatorgenerated Thu Feb 09 16:54:14 CST 2012
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column role.status
     *
     * @return the value of role.status
     *
     * @abatorgenerated Thu Feb 09 16:54:14 CST 2012
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column role.status
     *
     * @param status the value for role.status
     *
     * @abatorgenerated Thu Feb 09 16:54:14 CST 2012
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
	public String getStatusLabel() {
		if(this.status==1){
			return "有效";
		}else{
			return "无效";
		}
		
	}
}