package com.nuoshi.console.domain.bbs;

public class RoleFunction {

    private Integer id;

 
    private Integer roleid;


    private Integer functionid;


    public Integer getId() {
        return id;
    }

  
    public void setId(Integer id) {
        this.id = id;
    }


    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column role_function.roleId
     *
     * @param roleid the value for role_function.roleId
     *
     * @abatorgenerated Thu Feb 09 16:54:45 CST 2012
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column role_function.functionId
     *
     * @return the value of role_function.functionId
     *
     * @abatorgenerated Thu Feb 09 16:54:45 CST 2012
     */
    public Integer getFunctionid() {
        return functionid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column role_function.functionId
     *
     * @param functionid the value for role_function.functionId
     *
     * @abatorgenerated Thu Feb 09 16:54:45 CST 2012
     */
    public void setFunctionid(Integer functionid) {
        this.functionid = functionid;
    }
}