package com.nuoshi.console.domain.bbs;

import java.io.Serializable;
import java.util.Date;

public class TfBbsThreads implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1303390935820151345L;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column tf_bbs_threads.id
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	private Integer id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column tf_bbs_threads.forum_id
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	
	private int elite;
	private String rreason;
	
	public int getElite() {
		return elite;
	}

	public void setElite(int elite) {
		this.elite = elite;
	}

	public String getRreason() {
		return rreason;
	}

	public void setRreason(String rreason) {
		this.rreason = rreason;
	}
	private int forumId;
	private String forumname;
	private String forumNo;
	
	public String getForumname() {
		return forumname;
	}

	public void setForumname(String forumname) {
		this.forumname = forumname;
	}

	public String getForumNo() {
		return forumNo;
	}

	public void setForumNo(String forumNo) {
		this.forumNo = forumNo;
	}

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column tf_bbs_threads.city_id
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	private Integer cityId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column tf_bbs_threads.author
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	private String author;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column tf_bbs_threads.author_id
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	private Integer authorId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column tf_bbs_threads.subject
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	private String subject;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column tf_bbs_threads.entry_date
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	private Date entryDate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column tf_bbs_threads.last_poster_id
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	private Integer lastPosterId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column tf_bbs_threads.last_poster_name
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	private String lastPosterName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column tf_bbs_threads.visible_role
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	private Byte visibleRole;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column tf_bbs_threads.views
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	private Integer views;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column tf_bbs_threads.replies
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	private Integer replies;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column tf_bbs_threads.display_order
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	private Integer displayOrder;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column tf_bbs_threads.images
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	private Integer images;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column tf_bbs_threads.modifiy_date
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	private Date modifiyDate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column tf_bbs_threads.post_status
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	private Integer status;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column tf_bbs_threads.verifytime
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	private Date verifytime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column tf_bbs_threads.verifier
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	private String verifier;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column tf_bbs_threads.url
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	private String url;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column tf_bbs_threads.id
	 * @return  the value of tf_bbs_threads.id
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column tf_bbs_threads.id
	 * @param id  the value for tf_bbs_threads.id
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column tf_bbs_threads.forum_id
	 * @return  the value of tf_bbs_threads.forum_id
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	public int getForumId() {
		return forumId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column tf_bbs_threads.forum_id
	 * @param forumId  the value for tf_bbs_threads.forum_id
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	public void setForumId(int forumId) {
		this.forumId = forumId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column tf_bbs_threads.city_id
	 * @return  the value of tf_bbs_threads.city_id
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	public Integer getCityId() {
		return cityId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column tf_bbs_threads.city_id
	 * @param cityId  the value for tf_bbs_threads.city_id
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column tf_bbs_threads.author
	 * @return  the value of tf_bbs_threads.author
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	public String getAuthor() {
		return author;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column tf_bbs_threads.author
	 * @param author  the value for tf_bbs_threads.author
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	public void setAuthor(String author) {
		this.author = author;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column tf_bbs_threads.author_id
	 * @return  the value of tf_bbs_threads.author_id
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	public Integer getAuthorId() {
		return authorId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column tf_bbs_threads.author_id
	 * @param authorId  the value for tf_bbs_threads.author_id
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	public void setAuthorId(Integer authorId) {
		this.authorId = authorId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column tf_bbs_threads.subject
	 * @return  the value of tf_bbs_threads.subject
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	public String getSubject() {
		return subject;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column tf_bbs_threads.subject
	 * @param subject  the value for tf_bbs_threads.subject
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	public void setSubject(String subject) {
		this.subject = subject;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column tf_bbs_threads.entry_date
	 * @return  the value of tf_bbs_threads.entry_date
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	public Date getEntryDate() {
		return entryDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column tf_bbs_threads.entry_date
	 * @param entryDate  the value for tf_bbs_threads.entry_date
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column tf_bbs_threads.last_poster_id
	 * @return  the value of tf_bbs_threads.last_poster_id
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	public Integer getLastPosterId() {
		return lastPosterId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column tf_bbs_threads.last_poster_id
	 * @param lastPosterId  the value for tf_bbs_threads.last_poster_id
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	public void setLastPosterId(Integer lastPosterId) {
		this.lastPosterId = lastPosterId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column tf_bbs_threads.last_poster_name
	 * @return  the value of tf_bbs_threads.last_poster_name
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	public String getLastPosterName() {
		return lastPosterName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column tf_bbs_threads.last_poster_name
	 * @param lastPosterName  the value for tf_bbs_threads.last_poster_name
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	public void setLastPosterName(String lastPosterName) {
		this.lastPosterName = lastPosterName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column tf_bbs_threads.visible_role
	 * @return  the value of tf_bbs_threads.visible_role
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	public Byte getVisibleRole() {
		return visibleRole;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column tf_bbs_threads.visible_role
	 * @param visibleRole  the value for tf_bbs_threads.visible_role
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	public void setVisibleRole(Byte visibleRole) {
		this.visibleRole = visibleRole;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column tf_bbs_threads.views
	 * @return  the value of tf_bbs_threads.views
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	public Integer getViews() {
		return views;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column tf_bbs_threads.views
	 * @param views  the value for tf_bbs_threads.views
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	public void setViews(Integer views) {
		this.views = views;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column tf_bbs_threads.replies
	 * @return  the value of tf_bbs_threads.replies
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	public Integer getReplies() {
		return replies;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column tf_bbs_threads.replies
	 * @param replies  the value for tf_bbs_threads.replies
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	public void setReplies(Integer replies) {
		this.replies = replies;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column tf_bbs_threads.display_order
	 * @return  the value of tf_bbs_threads.display_order
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	public Integer getDisplayOrder() {
		return displayOrder;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column tf_bbs_threads.display_order
	 * @param displayOrder  the value for tf_bbs_threads.display_order
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	public void setDisplayOrder(Integer displayOrder) {
		this.displayOrder = displayOrder;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column tf_bbs_threads.images
	 * @return  the value of tf_bbs_threads.images
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	public Integer getImages() {
		return images;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column tf_bbs_threads.images
	 * @param images  the value for tf_bbs_threads.images
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	public void setImages(Integer images) {
		this.images = images;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column tf_bbs_threads.modifiy_date
	 * @return  the value of tf_bbs_threads.modifiy_date
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	public Date getModifiyDate() {
		return modifiyDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column tf_bbs_threads.modifiy_date
	 * @param modifiyDate  the value for tf_bbs_threads.modifiy_date
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	public void setModifiyDate(Date modifiyDate) {
		this.modifiyDate = modifiyDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column tf_bbs_threads.post_status
	 * @return  the value of tf_bbs_threads.post_status
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column tf_bbs_threads.post_status
	 * @param postStatus  the value for tf_bbs_threads.post_status
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column tf_bbs_threads.verifytime
	 * @return  the value of tf_bbs_threads.verifytime
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	public Date getVerifytime() {
		return verifytime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column tf_bbs_threads.verifytime
	 * @param verifytime  the value for tf_bbs_threads.verifytime
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	public void setVerifytime(Date verifytime) {
		this.verifytime = verifytime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column tf_bbs_threads.verifier
	 * @return  the value of tf_bbs_threads.verifier
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	public String getVerifier() {
		return verifier;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column tf_bbs_threads.verifier
	 * @param verifier  the value for tf_bbs_threads.verifier
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	public void setVerifier(String verifier) {
		this.verifier = verifier;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column tf_bbs_threads.url
	 * @return  the value of tf_bbs_threads.url
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column tf_bbs_threads.url
	 * @param url  the value for tf_bbs_threads.url
	 * @abatorgenerated  Thu Jan 12 14:44:02 CST 2012
	 */
	public void setUrl(String url) {
		this.url = url;
	}
}