package com.nuoshi.console.domain.bbs;

import java.util.Date;

public class TfBbsPosts {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column tf_bbs_posts.id
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	private Integer id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column tf_bbs_posts.forum_id
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	
	private int elite;
	private String rreason;
	
	public int getElite() {
		return elite;
	}

	public void setElite(int elite) {
		this.elite = elite;
	}

	public String getRreason() {
		return rreason;
	}

	public void setRreason(String rreason) {
		this.rreason = rreason;
	}

	private int forumId;
	private String forumNo;
	private String forumname;
	public String getForumname() {
		return forumname;
	}

	public void setForumname(String forumname) {
		this.forumname = forumname;
	}
	public String getForumNo() {
		return forumNo;
	}

	public void setForumNo(String forumNo) {
		this.forumNo = forumNo;
	}

	public int getForumId() {
		return forumId;
	}

	public void setForumId(int forumId) {
		this.forumId = forumId;
	}

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column tf_bbs_posts.thread_id
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	private Integer threadId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column tf_bbs_posts.city_id
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	private Integer cityId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column tf_bbs_posts.first
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	private Byte first;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column tf_bbs_posts.author
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	private String author;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column tf_bbs_posts.author_id
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	private Integer authorId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column tf_bbs_posts.subject
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	private String subject;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column tf_bbs_posts.entry_date
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	private Date entryDate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column tf_bbs_posts.user_ip
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	private String userIp;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column tf_bbs_posts.post_status
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	private Integer status;
	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column tf_bbs_posts.verifytime
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	private Date verifytime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column tf_bbs_posts.verifier
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	private String verifier;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column tf_bbs_posts.url
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	private String url;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column tf_bbs_posts.message
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	private String message;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column tf_bbs_posts.id
	 * @return  the value of tf_bbs_posts.id
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column tf_bbs_posts.id
	 * @param id  the value for tf_bbs_posts.id
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column tf_bbs_posts.thread_id
	 * @return  the value of tf_bbs_posts.thread_id
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	public Integer getThreadId() {
		return threadId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column tf_bbs_posts.thread_id
	 * @param threadId  the value for tf_bbs_posts.thread_id
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	public void setThreadId(Integer threadId) {
		this.threadId = threadId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column tf_bbs_posts.city_id
	 * @return  the value of tf_bbs_posts.city_id
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	public Integer getCityId() {
		return cityId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column tf_bbs_posts.city_id
	 * @param cityId  the value for tf_bbs_posts.city_id
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column tf_bbs_posts.first
	 * @return  the value of tf_bbs_posts.first
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	public Byte getFirst() {
		return first;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column tf_bbs_posts.first
	 * @param first  the value for tf_bbs_posts.first
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	public void setFirst(Byte first) {
		this.first = first;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column tf_bbs_posts.author
	 * @return  the value of tf_bbs_posts.author
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	public String getAuthor() {
		return author;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column tf_bbs_posts.author
	 * @param author  the value for tf_bbs_posts.author
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	public void setAuthor(String author) {
		this.author = author;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column tf_bbs_posts.author_id
	 * @return  the value of tf_bbs_posts.author_id
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	public Integer getAuthorId() {
		return authorId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column tf_bbs_posts.author_id
	 * @param authorId  the value for tf_bbs_posts.author_id
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	public void setAuthorId(Integer authorId) {
		this.authorId = authorId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column tf_bbs_posts.subject
	 * @return  the value of tf_bbs_posts.subject
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	public String getSubject() {
		return subject;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column tf_bbs_posts.subject
	 * @param subject  the value for tf_bbs_posts.subject
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	public void setSubject(String subject) {
		this.subject = subject;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column tf_bbs_posts.entry_date
	 * @return  the value of tf_bbs_posts.entry_date
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	public Date getEntryDate() {
		return entryDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column tf_bbs_posts.entry_date
	 * @param entryDate  the value for tf_bbs_posts.entry_date
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column tf_bbs_posts.user_ip
	 * @return  the value of tf_bbs_posts.user_ip
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	public String getUserIp() {
		return userIp;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column tf_bbs_posts.user_ip
	 * @param userIp  the value for tf_bbs_posts.user_ip
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}



	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column tf_bbs_posts.verifytime
	 * @return  the value of tf_bbs_posts.verifytime
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	public Date getVerifytime() {
		return verifytime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column tf_bbs_posts.verifytime
	 * @param verifytime  the value for tf_bbs_posts.verifytime
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	public void setVerifytime(Date verifytime) {
		this.verifytime = verifytime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column tf_bbs_posts.verifier
	 * @return  the value of tf_bbs_posts.verifier
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	public String getVerifier() {
		return verifier;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column tf_bbs_posts.verifier
	 * @param verifier  the value for tf_bbs_posts.verifier
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	public void setVerifier(String verifier) {
		this.verifier = verifier;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column tf_bbs_posts.url
	 * @return  the value of tf_bbs_posts.url
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column tf_bbs_posts.url
	 * @param url  the value for tf_bbs_posts.url
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column tf_bbs_posts.message
	 * @return  the value of tf_bbs_posts.message
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	public String getMessage() {
		return message;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column tf_bbs_posts.message
	 * @param message  the value for tf_bbs_posts.message
	 * @abatorgenerated  Thu Jan 12 14:43:46 CST 2012
	 */
	public void setMessage(String message) {
		this.message = message;
	}
}