package com.nuoshi.console.domain.bbs;

public class UserRole {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user_role.id
     *
     * @abatorgenerated Thu Feb 09 16:55:05 CST 2012
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user_role.userId
     *
     * @abatorgenerated Thu Feb 09 16:55:05 CST 2012
     */
    private Integer userid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user_role.roleId
     *
     * @abatorgenerated Thu Feb 09 16:55:05 CST 2012
     */
    private Integer roleid;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user_role.id
     *
     * @return the value of user_role.id
     *
     * @abatorgenerated Thu Feb 09 16:55:05 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user_role.id
     *
     * @param id the value for user_role.id
     *
     * @abatorgenerated Thu Feb 09 16:55:05 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user_role.userId
     *
     * @return the value of user_role.userId
     *
     * @abatorgenerated Thu Feb 09 16:55:05 CST 2012
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user_role.userId
     *
     * @param userid the value for user_role.userId
     *
     * @abatorgenerated Thu Feb 09 16:55:05 CST 2012
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user_role.roleId
     *
     * @return the value of user_role.roleId
     *
     * @abatorgenerated Thu Feb 09 16:55:05 CST 2012
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user_role.roleId
     *
     * @param roleid the value for user_role.roleId
     *
     * @abatorgenerated Thu Feb 09 16:55:05 CST 2012
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }
}